### ISSUE TITLE
Update linting rules

### ISSUE THREAD

**Issue by valentin-radulescu-hs** [uberVU/mocha-mugshot-reporter#24]
## Deliverables

- Enforce the same coding style as mugshot

#### Prerequisites
- [mugshot lint rules](https://github.com/uberVU/mugshot/blob/master/.eslintrc)

#### TODO
- [x] TBD

**Comment by valentin-radulescu-hs** [comment]
cc: @adela-istrate-hs

**Comment by adela-istrate-hs** [comment]
@flavius-tirnacop-hs @catalin-miron-hs Can I merge this into the base branch?
