### ISSUE TITLE
Improve bundled files

### ISSUE THREAD

**Issue by adela-istrate-hs** [uberVU/mocha-mugshot-reporter#40]
### Need
```gherkin
As a developer
I want git to ignore all bundled files
But I don't want git to ignore index.html
```

### Solution
Put bundled files in a separate folder and ignore that.
Make a bundle file for every bootstrap glyphicon format for better browser support.
Refactor the output config and include path: './statics' so that we can get rid of statics/.

**Comment by adela-istrate-hs** [comment]
@valentin-radulescu-hs @andrei-picus-hs Can you review?

**Comment by valentin-radulescu-hs** [comment]
@adela-istrate-hs Please make a PR for us to review
